# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='envelope.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=b'Z=github.com/tokenized/envelope/pkg/golang/envelope/v0/protobuf',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x65nvelope.proto\x12\x08protobuf\"\x98\x01\n\x08\x45nvelope\x12\x0f\n\x07Version\x18\x01 \x01(\x04\x12\x0c\n\x04Type\x18\x02 \x01(\x0c\x12\x12\n\nIdentifier\x18\x03 \x01(\x0c\x12\"\n\x07MetaNet\x18\x04 \x01(\x0b\x32\x11.protobuf.MetaNet\x12\x35\n\x11\x45ncryptedPayloads\x18\x05 \x03(\x0b\x32\x1a.protobuf.EncryptedPayload\"(\n\x07MetaNet\x12\r\n\x05Index\x18\x01 \x01(\r\x12\x0e\n\x06Parent\x18\x02 \x01(\x0c\"r\n\x10\x45ncryptedPayload\x12\x0e\n\x06Sender\x18\x01 \x01(\r\x12%\n\tReceivers\x18\x02 \x03(\x0b\x32\x12.protobuf.Receiver\x12\x0f\n\x07Payload\x18\x03 \x01(\x0c\x12\x16\n\x0e\x45ncryptionType\x18\x04 \x01(\r\"/\n\x08Receiver\x12\r\n\x05Index\x18\x01 \x01(\r\x12\x14\n\x0c\x45ncryptedKey\x18\x02 \x01(\x0c\x42?Z=github.com/tokenized/envelope/pkg/golang/envelope/v0/protobufb\x06proto3'
)




_ENVELOPE = _descriptor.Descriptor(
  name='Envelope',
  full_name='protobuf.Envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Version', full_name='protobuf.Envelope.Version', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Type', full_name='protobuf.Envelope.Type', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Identifier', full_name='protobuf.Envelope.Identifier', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MetaNet', full_name='protobuf.Envelope.MetaNet', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EncryptedPayloads', full_name='protobuf.Envelope.EncryptedPayloads', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=181,
)


_METANET = _descriptor.Descriptor(
  name='MetaNet',
  full_name='protobuf.MetaNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Index', full_name='protobuf.MetaNet.Index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Parent', full_name='protobuf.MetaNet.Parent', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=223,
)


_ENCRYPTEDPAYLOAD = _descriptor.Descriptor(
  name='EncryptedPayload',
  full_name='protobuf.EncryptedPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Sender', full_name='protobuf.EncryptedPayload.Sender', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Receivers', full_name='protobuf.EncryptedPayload.Receivers', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Payload', full_name='protobuf.EncryptedPayload.Payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EncryptionType', full_name='protobuf.EncryptedPayload.EncryptionType', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=339,
)


_RECEIVER = _descriptor.Descriptor(
  name='Receiver',
  full_name='protobuf.Receiver',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Index', full_name='protobuf.Receiver.Index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='EncryptedKey', full_name='protobuf.Receiver.EncryptedKey', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=388,
)

_ENVELOPE.fields_by_name['MetaNet'].message_type = _METANET
_ENVELOPE.fields_by_name['EncryptedPayloads'].message_type = _ENCRYPTEDPAYLOAD
_ENCRYPTEDPAYLOAD.fields_by_name['Receivers'].message_type = _RECEIVER
DESCRIPTOR.message_types_by_name['Envelope'] = _ENVELOPE
DESCRIPTOR.message_types_by_name['MetaNet'] = _METANET
DESCRIPTOR.message_types_by_name['EncryptedPayload'] = _ENCRYPTEDPAYLOAD
DESCRIPTOR.message_types_by_name['Receiver'] = _RECEIVER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Envelope = _reflection.GeneratedProtocolMessageType('Envelope', (_message.Message,), {
  'DESCRIPTOR' : _ENVELOPE,
  '__module__' : 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.Envelope)
  })
_sym_db.RegisterMessage(Envelope)

MetaNet = _reflection.GeneratedProtocolMessageType('MetaNet', (_message.Message,), {
  'DESCRIPTOR' : _METANET,
  '__module__' : 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.MetaNet)
  })
_sym_db.RegisterMessage(MetaNet)

EncryptedPayload = _reflection.GeneratedProtocolMessageType('EncryptedPayload', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDPAYLOAD,
  '__module__' : 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.EncryptedPayload)
  })
_sym_db.RegisterMessage(EncryptedPayload)

Receiver = _reflection.GeneratedProtocolMessageType('Receiver', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVER,
  '__module__' : 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.Receiver)
  })
_sym_db.RegisterMessage(Receiver)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
